name: Retail News Pipeline

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 13 * * *'  # 7:00 PM IST

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: pip install feedparser

      - name: Run
        run: python fetch_news.py

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "update" || echo "no changes"
          git push
