name: Retail Intelligence Pipeline

on:
  schedule:

    # 9:00 AM IST
    - cron: '30 3 * * *'

    # 7:00 PM IST
    - cron: '30 13 * * *'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install feedparser

      - name: Run News Engine
        run: python fetch_news.py

      - name: Commit Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .

          git commit -m "Retail intelligence update" || echo "No changes"

          git push
